name 'wlzookeeper'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures wlzookeeper'
long_description 'Installs/Configures wlzookeeper'
version '0.1.0'